site_name: Snowman
site_description: Python model and query builder for Snowflake
theme:
  name: material
  language: en
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"
  features:
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.tabs
    - navigation.path

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
repo_name: yassun7010/snowman-py
repo_url: https://github.com/yassun7010/snowman-py
site_url: https://yassun7010.github.io/snowman-py/
edit_uri: edit/main/docs/
plugins:
  - search
  - autorefs
  - awesome-pages:
  - inline-svg:
  - exclude:
      glob:
        - "**/.pytest_cache/*"
  - social
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            show_root_heading: true
            show_bases: false
            heading_level: 2
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            filters: ["!^_"]
            group_by_category: true
            extensions:
              - griffe_inherited_docstrings
markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Welcome: index.md
  - User Guide:
      - Installation: guide/installation.md
      - CLI Tool:
          - Usage: guide/cli_tool/index.md
          - Configuration: guide/cli_tool/configuration.md
      - Query Builder: guide/query_builder.md
