# [snowq](https://github.com/yassun7010/snowq)
#:schema https://raw.githubusercontent.com/yassun7010/snowq/main/docs/config.schema.json

[connection]
account = { env = "SNOWFLAKE_ACCOUNT" }
user = { env = "SNOWFLAKE_USER" }
password = { env = "SNOWFLAKE_PASSWORD" }
role = { env = "SNOWFLAKE_ROLE" }
database = { env = "SNOWFLAKE_DATABASE" }
schema = { env = "SNOWFLAKE_SCHEMA" }
warehouse = { env = "SNOWFLAKE_WAREHOUSE" }

[model]
output_dir = "src/snowq_sample/schema"

[pydantic]
# model_name_suffix = "Model"
