#
# Code generated by snowman; DO NOT EDIT.
#
# For more information about snowman,
# please refer to https://github.com/yassun7010/snowman-py .
#

import dataclasses
import typing

import snowman


@dataclasses.dataclass
class _UserColumnAccessor:
    id: snowman.Column[snowman.datatype.INTEGER]
    """User ID"""

    name: snowman.Column[snowman.datatype.TEXT]
    """User Name"""

    age: snowman.Column[snowman.datatype.INTEGER | None]
    """User Age"""

    created_at: snowman.Column[snowman.datatype.TIMESTAMP_TZ]
    """Created At"""


class _UserInsertTypedDict(typing.TypedDict):
    id: snowman.datatype.INTEGER
    """User ID"""

    name: snowman.datatype.TEXT
    """User Name"""

    age: typing.NotRequired[snowman.datatype.INTEGER | None]
    """User Age"""

    created_at: typing.NotRequired[snowman.datatype.TIMESTAMP_TZ]
    """Created At"""


class _UserUpdateTypedDict(typing.TypedDict):
    id: typing.NotRequired[snowman.datatype.INTEGER]
    """User ID"""

    name: typing.NotRequired[snowman.datatype.TEXT]
    """User Name"""

    age: typing.NotRequired[snowman.datatype.INTEGER | None]
    """User Age"""

    created_at: typing.NotRequired[snowman.datatype.TIMESTAMP_TZ]
    """Created At"""
