name: CI Python

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v2
      - run: rye format
      - run: rye lint
      - run: rye test
