name: CI Python

on:
  push:
    branches:
      - main
    paths:
      - python/**
  pull_request:
    branches:
      - main
    paths:
      - python/**
  workflow_dispatch:

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v2
      - run: rye format --check
      - run: rye lint
      - run: rye test
      - run: rye run typecheck
